In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('50_Startups.csv')

In [4]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [5]:
X = df.iloc[:,:-1].values
y= df.iloc[:,-1].values

In [7]:
X[:5]

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida']], dtype=object)

In [8]:
y[:5]

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94])

In [9]:
df.isna().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[3])],remainder='passthrough')
X= ct.fit_transform(X)

In [12]:
X[:5]

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42]], dtype=object)

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [14]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [15]:
y_pred = lr.predict(X_test)

In [16]:
y_pred

array([126362.87908251,  84608.45383642,  99677.49425156,  46357.46068584,
       128750.48288497,  50912.41741905, 109741.35032702, 100643.24281644,
        97599.275746  , 113097.42524438])

In [18]:
np.set_printoptions(precision=2)
np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1)

array([[126362.88, 134307.35],
       [ 84608.45,  81005.76],
       [ 99677.49,  99937.59],
       [ 46357.46,  64926.08],
       [128750.48, 125370.37],
       [ 50912.42,  35673.41],
       [109741.35, 105733.54],
       [100643.24, 107404.34],
       [ 97599.28,  97427.84],
       [113097.43, 122776.86]])