In [1]:
import numpy as np

In [23]:
list_1  = [1,2,3]

In [24]:
a1 = np.array(list_1)

In [9]:
type(one_d_array)

numpy.ndarray

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
random_array = np.random.randint(2,10, size= (4,3))
random_array

array([[9, 6, 9],
       [7, 6, 9],
       [2, 9, 6],
       [4, 6, 2]])

In [21]:
random_array[:2,1:]

array([[6, 9],
       [6, 9]])

In [17]:
random_3d_array = np.random.randn(2,3,4)
random_3d_array

array([[[-0.85712781, -1.09533321,  0.62510769,  0.20074633],
        [-0.6658919 ,  0.53254578, -0.85234217,  0.20381006],
        [ 0.90378772,  2.37282449,  0.16199496,  1.43347712]],

       [[-1.06613335, -1.97631418,  0.52747512,  0.68737732],
        [ 0.15918378, -0.23406153, -0.64557915,  0.14019052],
        [ 0.2893491 ,  0.34975311,  0.8330752 , -0.91531821]]])

In [20]:
random_3d_array[:1,2:,:2]

array([[[0.90378772, 2.37282449]]])

In [25]:
a1

array([1, 2, 3])

In [27]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [28]:
a1 * ones

array([1., 2., 3.])

In [32]:
a2 = np.random.randint(2,10, size= (4,3))
a2

array([[8, 2, 8],
       [5, 9, 8],
       [5, 9, 4],
       [8, 3, 9]])

In [31]:
a1 * a2

array([[ 9, 14, 12],
       [ 6,  8, 21],
       [ 7, 12,  9],
       [ 7, 18, 21]])

In [33]:
np.random.random(30)

array([0.16430231, 0.43240361, 0.11246156, 0.41410698, 0.76661972,
       0.87685413, 0.68805967, 0.31897203, 0.62069695, 0.21194371,
       0.93630201, 0.82373985, 0.40604252, 0.73003062, 0.46717471,
       0.84498748, 0.61954008, 0.57026843, 0.20538292, 0.78888748,
       0.51297529, 0.76304023, 0.74729937, 0.98380753, 0.40040635,
       0.37385332, 0.24780436, 0.70796451, 0.76939266, 0.49989652])

In [35]:
r1 =np.random.randint(2,50, (3,4))

In [36]:
r1.reshape(3,4,1)

array([[[34],
        [37],
        [28],
        [14]],

       [[33],
        [39],
        [31],
        [33]],

       [[42],
        [37],
        [ 8],
        [17]]])